# Generated by Django 3.2.25 on 2025-09-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('biblio_id', models.IntegerField()),
                ('member_id', models.CharField(max_length=20)),
                ('comment', models.TextField()),
                ('input_date', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=100)),
                ('gender', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Male'), (2, 'Female')])),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('member_type_id', models.IntegerField(blank=True, null=True)),
                ('member_address', models.CharField(blank=True, max_length=255, null=True)),
                ('member_mail_address', models.CharField(blank=True, max_length=255, null=True)),
                ('member_email', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('inst_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_new', models.IntegerField(blank=True, null=True)),
                ('member_image', models.CharField(blank=True, max_length=200, null=True)),
                ('pin', models.CharField(blank=True, max_length=50, null=True)),
                ('member_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('member_fax', models.CharField(blank=True, max_length=50, null=True)),
                ('member_since_date', models.DateField(blank=True, null=True)),
                ('register_date', models.DateField(blank=True, null=True)),
                ('expire_date', models.DateField()),
                ('member_notes', models.TextField(blank=True, null=True)),
                ('is_pending', models.SmallIntegerField(default=0)),
                ('mpasswd', models.CharField(blank=True, max_length=64, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.CharField(blank=True, max_length=20, null=True)),
                ('input_date', models.DateField(blank=True, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='MemberCustom',
            fields=[
                ('member_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'member_custom',
            },
        ),
        migrations.CreateModel(
            name='MstMemberType',
            fields=[
                ('member_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_type_name', models.CharField(max_length=50, unique=True)),
                ('loan_limit', models.IntegerField()),
                ('loan_periode', models.IntegerField()),
                ('enable_reserve', models.IntegerField(default=0)),
                ('reserve_limit', models.IntegerField(default=0)),
                ('member_periode', models.IntegerField()),
                ('reborrow_limit', models.IntegerField()),
                ('fine_each_day', models.IntegerField()),
                ('grace_periode', models.SmallIntegerField(default=0)),
                ('input_date', models.DateField()),
                ('last_update', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_member_type',
            },
        ),
        migrations.CreateModel(
            name='VisitorCount',
            fields=[
                ('visitor_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_id', models.CharField(blank=True, max_length=20, null=True)),
                ('member_name', models.CharField(max_length=255)),
                ('institution', models.CharField(blank=True, max_length=100, null=True)),
                ('checkin_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'visitor_count',
            },
        ),
        migrations.AddIndex(
            model_name='visitorcount',
            index=models.Index(fields=['member_id'], name='visitor_cou_member__86f33b_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['member_name'], name='member_member__d7211b_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['member_type_id'], name='member_member__acfc92_idx'),
        ),
    ]
