# Generated by Django 3.2.25 on 2025-09-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='ktp_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
