# Generated by Django 4.2.24 on 2025-09-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foto_diri',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='foto_ktp',
            field=models.ImageField(blank=True, null=True, upload_to='ktp_photos/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='institusi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='keanggotaan',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('PREMIUM', 'Premium'), ('VIP', 'VIP')], default='REGULAR', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tempat_lahir',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
