# Generated by Django 3.2.25 on 2025-09-17 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20250916_0332'),
    ]

    operations = [
    ]
