# Generated by Django 3.2.25 on 2025-09-17 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_fix_password_field_length'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE member MODIFY COLUMN mpasswd VARCHAR(255);",
            reverse_sql="ALTER TABLE member MODIFY COLUMN mpasswd VARCHAR(64);"
        ),
    ]
