# Generated by Django 4.2.7 on 2025-12-13 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_fix_password_field_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mstmembertype',
            options={'managed': False},
        ),
    ]
