# Generated by Django 3.2.25 on 2025-09-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('module_id', models.IntegerField()),
                ('menus', models.JSONField(blank=True, null=True)),
                ('r', models.IntegerField(default=0)),
                ('w', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'group_access',
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('staff', 'Staff'), ('member', 'Member'), ('system', 'System')], default='staff', max_length=20)),
                ('id', models.CharField(blank=True, max_length=50, null=True)),
                ('log_location', models.CharField(max_length=50)),
                ('sub_module', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.CharField(blank=True, max_length=50, null=True)),
                ('log_msg', models.TextField()),
                ('log_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'system_log',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('realname', models.CharField(max_length=100)),
                ('passwd', models.CharField(max_length=64)),
                ('fa', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('user_type', models.SmallIntegerField(blank=True, null=True)),
                ('user_image', models.CharField(blank=True, max_length=250, null=True)),
                ('social_media', models.TextField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.CharField(blank=True, max_length=15, null=True)),
                ('groups', models.CharField(blank=True, max_length=200, null=True)),
                ('forgot', models.CharField(blank=True, max_length=80, null=True)),
                ('admin_template', models.TextField(blank=True, null=True)),
                ('input_date', models.DateField(blank=True, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=30, unique=True)),
                ('input_date', models.DateField(blank=True, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_group',
            },
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['log_type'], name='system_log_log_typ_822019_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['id'], name='system_log_id_306723_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupaccess',
            unique_together={('group_id', 'module_id')},
        ),
    ]
