# Generated by Django 4.2.24 on 2025-09-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
