# Generated by Django 4.2.7 on 2025-12-14 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fa',
        ),
    ]
