# Generated by Django 3.2.25 on 2025-09-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('backup_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=0)),
                ('backup_time', models.DateTimeField()),
                ('backup_file', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'backup_log',
            },
        ),
        migrations.CreateModel(
            name='Biblio',
            fields=[
                ('biblio_id', models.AutoField(primary_key=True, serialize=False)),
                ('gmd_id', models.IntegerField(blank=True, null=True)),
                ('title', models.TextField()),
                ('sor', models.CharField(blank=True, max_length=200, null=True)),
                ('edition', models.CharField(blank=True, max_length=50, null=True)),
                ('isbn_issn', models.CharField(blank=True, max_length=32, null=True)),
                ('publisher_id', models.IntegerField(blank=True, null=True)),
                ('publish_year', models.CharField(blank=True, max_length=20, null=True)),
                ('collation', models.CharField(blank=True, max_length=50, null=True)),
                ('series_title', models.CharField(blank=True, max_length=200, null=True)),
                ('call_number', models.CharField(blank=True, max_length=50, null=True)),
                ('language_id', models.CharField(default='en', max_length=5)),
                ('source', models.CharField(blank=True, max_length=3, null=True)),
                ('publish_place_id', models.IntegerField(blank=True, null=True)),
                ('classification', models.CharField(blank=True, max_length=40, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('file_att', models.CharField(blank=True, max_length=255, null=True)),
                ('opac_hide', models.SmallIntegerField(default=0)),
                ('promoted', models.SmallIntegerField(default=0)),
                ('labels', models.TextField(blank=True, null=True)),
                ('frequency_id', models.IntegerField(default=0)),
                ('spec_detail_info', models.TextField(blank=True, null=True)),
                ('content_type_id', models.IntegerField(blank=True, null=True)),
                ('media_type_id', models.IntegerField(blank=True, null=True)),
                ('carrier_type_id', models.IntegerField(blank=True, null=True)),
                ('input_date', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('uid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'biblio',
            },
        ),
        migrations.CreateModel(
            name='BiblioAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biblio_id', models.IntegerField()),
                ('file_id', models.IntegerField()),
                ('placement', models.CharField(blank=True, choices=[('link', 'Link'), ('popup', 'Popup'), ('embed', 'Embed')], max_length=20, null=True)),
                ('access_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=10)),
                ('access_limit', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'biblio_attachment',
            },
        ),
        migrations.CreateModel(
            name='BiblioAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biblio_id', models.IntegerField()),
                ('author_id', models.IntegerField()),
                ('level', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'biblio_author',
            },
        ),
        migrations.CreateModel(
            name='BiblioCustom',
            fields=[
                ('biblio_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'biblio_custom',
            },
        ),
        migrations.CreateModel(
            name='BiblioLog',
            fields=[
                ('biblio_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('biblio_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('realname', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('ip', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=50)),
                ('affectedrow', models.CharField(max_length=50)),
                ('rawdata', models.TextField()),
                ('additional_information', models.TextField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'biblio_log',
            },
        ),
        migrations.CreateModel(
            name='BiblioRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biblio_id', models.IntegerField()),
                ('rel_biblio_id', models.IntegerField()),
                ('rel_type', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'biblio_relation',
            },
        ),
        migrations.CreateModel(
            name='BiblioTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biblio_id', models.IntegerField()),
                ('topic_id', models.IntegerField()),
                ('level', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'biblio_topic',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('content_title', models.CharField(max_length=255)),
                ('content_desc', models.TextField()),
                ('content_path', models.CharField(max_length=20, unique=True)),
                ('is_news', models.SmallIntegerField(blank=True, null=True)),
                ('input_date', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
                ('content_ownpage', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='1', max_length=1)),
            ],
            options={
                'db_table': 'content',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_title', models.TextField()),
                ('file_name', models.TextField()),
                ('file_url', models.TextField(blank=True, null=True)),
                ('file_dir', models.TextField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file_desc', models.TextField(blank=True, null=True)),
                ('file_key', models.TextField(blank=True, null=True)),
                ('uploader_id', models.IntegerField()),
                ('input_date', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='FilesRead',
            fields=[
                ('filelog_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_id', models.IntegerField()),
                ('date_read', models.DateTimeField()),
                ('member_id', models.CharField(blank=True, max_length=20, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('client_ip', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'files_read',
            },
        ),
        migrations.CreateModel(
            name='Fines',
            fields=[
                ('fines_id', models.AutoField(primary_key=True, serialize=False)),
                ('fines_date', models.DateField()),
                ('member_id', models.CharField(max_length=20)),
                ('debet', models.IntegerField(default=0)),
                ('credit', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'fines',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('holiday_id', models.AutoField(primary_key=True, serialize=False)),
                ('holiday_dayname', models.CharField(max_length=20)),
                ('holiday_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'holiday',
            },
        ),
        migrations.CreateModel(
            name='IndexDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.IntegerField()),
                ('word_id', models.BigIntegerField()),
                ('location', models.CharField(max_length=50)),
                ('hit_count', models.IntegerField()),
            ],
            options={
                'db_table': 'index_documents',
            },
        ),
        migrations.CreateModel(
            name='IndexWords',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=50)),
                ('num_hits', models.IntegerField()),
                ('doc_hits', models.IntegerField()),
            ],
            options={
                'db_table': 'index_words',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('biblio_id', models.IntegerField(blank=True, null=True)),
                ('call_number', models.CharField(blank=True, max_length=50, null=True)),
                ('coll_type_id', models.IntegerField(blank=True, null=True)),
                ('item_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('inventory_code', models.CharField(blank=True, max_length=200, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('supplier_id', models.CharField(blank=True, max_length=6, null=True)),
                ('order_no', models.CharField(blank=True, max_length=20, null=True)),
                ('location_id', models.CharField(blank=True, max_length=3, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('item_status_id', models.CharField(blank=True, max_length=3, null=True)),
                ('site', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.IntegerField(default=0)),
                ('invoice', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('price_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('input_date', models.DateTimeField()),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('uid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('kardex_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_expected', models.DateField()),
                ('date_received', models.DateField(blank=True, null=True)),
                ('seq_number', models.CharField(blank=True, max_length=25, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('serial_id', models.IntegerField(blank=True, null=True)),
                ('input_date', models.DateField()),
                ('last_update', models.DateField()),
            ],
            options={
                'db_table': 'kardex',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(blank=True, max_length=20, null=True)),
                ('member_id', models.CharField(blank=True, max_length=20, null=True)),
                ('loan_date', models.DateField()),
                ('due_date', models.DateField()),
                ('renewed', models.IntegerField(default=0)),
                ('loan_rules_id', models.IntegerField(default=0)),
                ('actual', models.DateField(blank=True, null=True)),
                ('is_lent', models.IntegerField(default=0)),
                ('is_return', models.IntegerField(default=0)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('input_date', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('uid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'loan',
            },
        ),
        migrations.CreateModel(
            name='LoanHistory',
            fields=[
                ('loan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(blank=True, max_length=20, null=True)),
                ('biblio_id', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('call_number', models.CharField(blank=True, max_length=50, null=True)),
                ('classification', models.CharField(blank=True, max_length=40, null=True)),
                ('gmd_name', models.CharField(blank=True, max_length=30, null=True)),
                ('language_name', models.CharField(blank=True, max_length=20, null=True)),
                ('location_name', models.CharField(blank=True, max_length=100, null=True)),
                ('collection_type_name', models.CharField(blank=True, max_length=100, null=True)),
                ('member_id', models.CharField(blank=True, max_length=20, null=True)),
                ('member_name', models.CharField(blank=True, max_length=100, null=True)),
                ('member_type_name', models.CharField(blank=True, max_length=64, null=True)),
                ('loan_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('renewed', models.IntegerField(default=0)),
                ('is_lent', models.IntegerField(default=0)),
                ('is_return', models.IntegerField(default=0)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('input_date', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'loan_history',
            },
        ),
        migrations.CreateModel(
            name='MstAuthor',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=100, unique=True)),
                ('author_year', models.CharField(blank=True, max_length=20, null=True)),
                ('authority_type', models.CharField(choices=[('p', 'Person'), ('o', 'Organization'), ('c', 'Conference')], default='p', max_length=1)),
                ('auth_list', models.CharField(blank=True, max_length=20, null=True)),
                ('input_date', models.DateField()),
                ('last_update', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_author',
            },
        ),
        migrations.CreateModel(
            name='MstCarrierType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('carrier_type', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=5)),
                ('code2', models.CharField(max_length=1)),
                ('input_date', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'mst_carrier_type',
            },
        ),
        migrations.CreateModel(
            name='MstCollType',
            fields=[
                ('coll_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('coll_type_name', models.CharField(max_length=30, unique=True)),
                ('input_date', models.DateField(blank=True, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_coll_type',
            },
        ),
        migrations.CreateModel(
            name='MstContentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content_type', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=5)),
                ('code2', models.CharField(max_length=1)),
                ('input_date', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'mst_content_type',
            },
        ),
        migrations.CreateModel(
            name='MstCustomField',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('primary_table', models.CharField(blank=True, max_length=100, null=True)),
                ('dbfield', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('type', models.CharField(choices=[('text', 'Text'), ('checklist', 'Checklist'), ('numeric', 'Numeric'), ('dropdown', 'Dropdown'), ('longtext', 'Long Text'), ('choice', 'Choice'), ('date', 'Date')], max_length=20)),
                ('default', models.CharField(blank=True, max_length=80, null=True)),
                ('max', models.IntegerField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('indexed', models.SmallIntegerField(blank=True, null=True)),
                ('class_field', models.CharField(blank=True, max_length=100, null=True)),
                ('is_public', models.SmallIntegerField(blank=True, null=True)),
                ('width', models.IntegerField(default=100)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_custom_field',
            },
        ),
        migrations.CreateModel(
            name='MstFrequency',
            fields=[
                ('frequency_id', models.AutoField(primary_key=True, serialize=False)),
                ('frequency', models.CharField(max_length=25)),
                ('language_prefix', models.CharField(blank=True, max_length=5, null=True)),
                ('time_increment', models.SmallIntegerField(blank=True, null=True)),
                ('time_unit', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='day', max_length=10)),
                ('input_date', models.DateField()),
                ('last_update', models.DateField()),
            ],
            options={
                'db_table': 'mst_frequency',
            },
        ),
        migrations.CreateModel(
            name='MstGmd',
            fields=[
                ('gmd_id', models.AutoField(primary_key=True, serialize=False)),
                ('gmd_code', models.CharField(blank=True, max_length=3, null=True, unique=True)),
                ('gmd_name', models.CharField(max_length=30, unique=True)),
                ('icon_image', models.CharField(blank=True, max_length=100, null=True)),
                ('input_date', models.DateField()),
                ('last_update', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_gmd',
            },
        ),
        migrations.CreateModel(
            name='MstItemStatus',
            fields=[
                ('item_status_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('item_status_name', models.CharField(max_length=30, unique=True)),
                ('rules', models.CharField(blank=True, max_length=255, null=True)),
                ('no_loan', models.SmallIntegerField(default=0)),
                ('skip_stock_take', models.SmallIntegerField(default=0)),
                ('input_date', models.DateField(blank=True, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_item_status',
            },
        ),
        migrations.CreateModel(
            name='MstLabel',
            fields=[
                ('label_id', models.AutoField(primary_key=True, serialize=False)),
                ('label_name', models.CharField(max_length=20, unique=True)),
                ('label_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('label_image', models.CharField(max_length=200)),
                ('input_date', models.DateField()),
                ('last_update', models.DateField()),
            ],
            options={
                'db_table': 'mst_label',
            },
        ),
        migrations.CreateModel(
            name='MstLanguage',
            fields=[
                ('language_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=20, unique=True)),
                ('input_date', models.DateField(blank=True, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_language',
            },
        ),
        migrations.CreateModel(
            name='MstLoanRules',
            fields=[
                ('loan_rules_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_type_id', models.IntegerField(default=0)),
                ('coll_type_id', models.IntegerField(default=0)),
                ('gmd_id', models.IntegerField(default=0)),
                ('loan_limit', models.IntegerField(default=0)),
                ('loan_periode', models.IntegerField(default=0)),
                ('reborrow_limit', models.IntegerField(default=0)),
                ('fine_each_day', models.IntegerField(default=0)),
                ('grace_periode', models.SmallIntegerField(default=0)),
                ('input_date', models.DateField(blank=True, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_loan_rules',
            },
        ),
        migrations.CreateModel(
            name='MstLocation',
            fields=[
                ('location_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('location_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('input_date', models.DateField()),
                ('last_update', models.DateField()),
            ],
            options={
                'db_table': 'mst_location',
            },
        ),
        migrations.CreateModel(
            name='MstMediaType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('media_type', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=5)),
                ('code2', models.CharField(max_length=1)),
                ('input_date', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'mst_media_type',
            },
        ),
        migrations.CreateModel(
            name='MstModule',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=50, unique=True)),
                ('module_path', models.CharField(blank=True, max_length=200, null=True)),
                ('module_desc', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'mst_module',
            },
        ),
        migrations.CreateModel(
            name='MstPlace',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=30, unique=True)),
                ('input_date', models.DateField(blank=True, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_place',
            },
        ),
        migrations.CreateModel(
            name='MstPublisher',
            fields=[
                ('publisher_id', models.AutoField(primary_key=True, serialize=False)),
                ('publisher_name', models.CharField(max_length=100, unique=True)),
                ('input_date', models.DateField(blank=True, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_publisher',
            },
        ),
        migrations.CreateModel(
            name='MstRelationTerm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rt_id', models.CharField(max_length=11)),
                ('rt_desc', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'mst_relation_term',
            },
        ),
        migrations.CreateModel(
            name='MstServers',
            fields=[
                ('server_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('uri', models.TextField()),
                ('server_type', models.SmallIntegerField(default=1)),
                ('input_date', models.DateTimeField()),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_servers',
            },
        ),
        migrations.CreateModel(
            name='MstSupplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=14, null=True)),
                ('contact', models.CharField(blank=True, max_length=30, null=True)),
                ('fax', models.CharField(blank=True, max_length=14, null=True)),
                ('account', models.CharField(blank=True, max_length=12, null=True)),
                ('e_mail', models.CharField(blank=True, max_length=80, null=True)),
                ('input_date', models.DateField(blank=True, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_supplier',
            },
        ),
        migrations.CreateModel(
            name='MstTopic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=50, unique=True)),
                ('topic_type', models.CharField(choices=[('t', 'Topic'), ('g', 'Geographic'), ('n', 'Name'), ('tm', 'Temporal'), ('gr', 'Genre'), ('oc', 'Occupation')], max_length=2)),
                ('auth_list', models.CharField(blank=True, max_length=20, null=True)),
                ('classification', models.CharField(max_length=50)),
                ('input_date', models.DateField(blank=True, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_topic',
            },
        ),
        migrations.CreateModel(
            name='MstVocCtrl',
            fields=[
                ('vocabolary_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_id', models.IntegerField()),
                ('rt_id', models.CharField(max_length=11)),
                ('related_topic_id', models.CharField(max_length=250)),
                ('scope', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mst_voc_ctrl',
            },
        ),
        migrations.CreateModel(
            name='Plugins',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('path', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('uid', models.IntegerField()),
            ],
            options={
                'db_table': 'plugins',
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('reserve_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_id', models.CharField(max_length=20)),
                ('biblio_id', models.IntegerField()),
                ('item_code', models.CharField(max_length=20)),
                ('reserve_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'reserve',
            },
        ),
        migrations.CreateModel(
            name='SearchBiblio',
            fields=[
                ('biblio_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('edition', models.CharField(blank=True, max_length=50, null=True)),
                ('isbn_issn', models.CharField(blank=True, max_length=20, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('topic', models.TextField(blank=True, null=True)),
                ('gmd', models.CharField(blank=True, max_length=30, null=True)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('publish_place', models.CharField(blank=True, max_length=30, null=True)),
                ('language', models.CharField(blank=True, max_length=20, null=True)),
                ('classification', models.CharField(blank=True, max_length=40, null=True)),
                ('spec_detail_info', models.TextField(blank=True, null=True)),
                ('carrier_type', models.CharField(max_length=100)),
                ('content_type', models.CharField(max_length=100)),
                ('media_type', models.CharField(max_length=100)),
                ('location', models.TextField(blank=True, null=True)),
                ('publish_year', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('series_title', models.TextField(blank=True, null=True)),
                ('items', models.TextField(blank=True, null=True)),
                ('collection_types', models.TextField(blank=True, null=True)),
                ('call_number', models.CharField(blank=True, max_length=50, null=True)),
                ('opac_hide', models.SmallIntegerField(default=0)),
                ('promoted', models.SmallIntegerField(default=0)),
                ('labels', models.TextField(blank=True, null=True)),
                ('collation', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('input_date', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'search_biblio',
            },
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('serial_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('period', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('biblio_id', models.IntegerField(blank=True, null=True)),
                ('gmd_id', models.IntegerField(blank=True, null=True)),
                ('input_date', models.DateField()),
                ('last_update', models.DateField()),
            ],
            options={
                'db_table': 'serial',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('setting_id', models.AutoField(primary_key=True, serialize=False)),
                ('setting_name', models.CharField(max_length=30, unique=True)),
                ('setting_value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'setting',
            },
        ),
        migrations.CreateModel(
            name='StockTake',
            fields=[
                ('stock_take_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_take_name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('init_user', models.CharField(max_length=50)),
                ('total_item_stock_taked', models.IntegerField(blank=True, null=True)),
                ('total_item_lost', models.IntegerField(blank=True, null=True)),
                ('total_item_exists', models.IntegerField(default=0)),
                ('total_item_loan', models.IntegerField(blank=True, null=True)),
                ('stock_take_users', models.TextField(blank=True, null=True)),
                ('is_active', models.IntegerField(default=0)),
                ('report_file', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'stock_take',
            },
        ),
        migrations.CreateModel(
            name='StockTakeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_take_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('item_code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('gmd_name', models.CharField(blank=True, max_length=30, null=True)),
                ('classification', models.CharField(blank=True, max_length=30, null=True)),
                ('coll_type_name', models.CharField(blank=True, max_length=30, null=True)),
                ('call_number', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('e', 'Exists'), ('m', 'Missing'), ('u', 'Unknown'), ('l', 'Lost')], default='m', max_length=10)),
                ('checked_by', models.CharField(max_length=50)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_take_item',
            },
        ),
        migrations.AddIndex(
            model_name='stocktakeitem',
            index=models.Index(fields=['item_code'], name='stock_take__item_co_0c2279_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktakeitem',
            index=models.Index(fields=['status'], name='stock_take__status_a16195_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktakeitem',
            index=models.Index(fields=['gmd_name', 'classification', 'coll_type_name', 'location'], name='stock_take__gmd_nam_273ab0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stocktakeitem',
            unique_together={('stock_take_id', 'item_id')},
        ),
        migrations.AddIndex(
            model_name='serial',
            index=models.Index(fields=['biblio_id'], name='serial_biblio__b519df_idx'),
        ),
        migrations.AddIndex(
            model_name='serial',
            index=models.Index(fields=['gmd_id'], name='serial_gmd_id_528908_idx'),
        ),
        migrations.AddIndex(
            model_name='searchbiblio',
            index=models.Index(fields=['gmd', 'publisher', 'publish_place', 'language', 'classification', 'publish_year', 'call_number'], name='search_bibl_gmd_d04b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='searchbiblio',
            index=models.Index(fields=['opac_hide', 'promoted'], name='search_bibl_opac_hi_bd1518_idx'),
        ),
        migrations.AddIndex(
            model_name='searchbiblio',
            index=models.Index(fields=['carrier_type', 'media_type', 'content_type'], name='search_bibl_carrier_3eb08d_idx'),
        ),
        migrations.AddIndex(
            model_name='reserve',
            index=models.Index(fields=['member_id', 'biblio_id'], name='reserve_member__aad5e2_idx'),
        ),
        migrations.AddIndex(
            model_name='reserve',
            index=models.Index(fields=['item_code'], name='reserve_item_co_2e491e_idx'),
        ),
        migrations.AddIndex(
            model_name='mstmediatype',
            index=models.Index(fields=['code'], name='mst_media_t_code_83afca_idx'),
        ),
        migrations.AddIndex(
            model_name='mstcontenttype',
            index=models.Index(fields=['code'], name='mst_content_code_e321db_idx'),
        ),
        migrations.AddIndex(
            model_name='mstcarriertype',
            index=models.Index(fields=['code'], name='mst_carrier_code_0467da_idx'),
        ),
        migrations.AddIndex(
            model_name='loanhistory',
            index=models.Index(fields=['member_name'], name='loan_histor_member__7a8074_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['item_code'], name='loan_item_co_98665e_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['member_id'], name='loan_member__9d2306_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['input_date', 'last_update', 'uid'], name='loan_input_d_ff9442_idx'),
        ),
        migrations.AddIndex(
            model_name='kardex',
            index=models.Index(fields=['serial_id'], name='kardex_serial__894732_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['uid'], name='item_uid_643e49_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['coll_type_id', 'location_id', 'item_status_id'], name='item_coll_ty_347499_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['biblio_id'], name='item_biblio__98cccc_idx'),
        ),
        migrations.AddIndex(
            model_name='indexdocuments',
            index=models.Index(fields=['document_id'], name='index_docum_documen_a8955f_idx'),
        ),
        migrations.AddIndex(
            model_name='indexdocuments',
            index=models.Index(fields=['word_id'], name='index_docum_word_id_11ddb2_idx'),
        ),
        migrations.AddIndex(
            model_name='indexdocuments',
            index=models.Index(fields=['location'], name='index_docum_locatio_ba039a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='indexdocuments',
            unique_together={('document_id', 'word_id', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('holiday_dayname', 'holiday_date')},
        ),
        migrations.AddIndex(
            model_name='fines',
            index=models.Index(fields=['member_id'], name='fines_member__71f3b0_idx'),
        ),
        migrations.AddIndex(
            model_name='files',
            index=models.Index(fields=['file_name'], name='files_file_na_85b89e_idx'),
        ),
        migrations.AddIndex(
            model_name='files',
            index=models.Index(fields=['file_dir'], name='files_file_di_3392bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bibliotopic',
            unique_together={('biblio_id', 'topic_id')},
        ),
        migrations.AlterUniqueTogether(
            name='bibliorelation',
            unique_together={('biblio_id', 'rel_biblio_id')},
        ),
        migrations.AddIndex(
            model_name='bibliolog',
            index=models.Index(fields=['realname'], name='biblio_log_realnam_56e9c8_idx'),
        ),
        migrations.AddIndex(
            model_name='bibliolog',
            index=models.Index(fields=['biblio_id'], name='biblio_log_biblio__91285e_idx'),
        ),
        migrations.AddIndex(
            model_name='bibliolog',
            index=models.Index(fields=['user_id'], name='biblio_log_user_id_8594e6_idx'),
        ),
        migrations.AddIndex(
            model_name='bibliolog',
            index=models.Index(fields=['ip'], name='biblio_log_ip_9f84b6_idx'),
        ),
        migrations.AddIndex(
            model_name='bibliolog',
            index=models.Index(fields=['action'], name='biblio_log_action_a0f77e_idx'),
        ),
        migrations.AddIndex(
            model_name='bibliolog',
            index=models.Index(fields=['affectedrow'], name='biblio_log_affecte_269e42_idx'),
        ),
        migrations.AddIndex(
            model_name='bibliolog',
            index=models.Index(fields=['date'], name='biblio_log_date_031c5e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='biblioauthor',
            unique_together={('biblio_id', 'author_id')},
        ),
        migrations.AddIndex(
            model_name='biblioattachment',
            index=models.Index(fields=['biblio_id'], name='biblio_atta_biblio__72d508_idx'),
        ),
        migrations.AddIndex(
            model_name='biblioattachment',
            index=models.Index(fields=['file_id'], name='biblio_atta_file_id_a8384c_idx'),
        ),
        migrations.AddIndex(
            model_name='biblioattachment',
            index=models.Index(fields=['biblio_id', 'file_id'], name='biblio_atta_biblio__438a63_idx'),
        ),
        migrations.AddIndex(
            model_name='biblio',
            index=models.Index(fields=['gmd_id', 'publisher_id', 'language_id', 'publish_place_id'], name='biblio_gmd_id_994f83_idx'),
        ),
        migrations.AddIndex(
            model_name='biblio',
            index=models.Index(fields=['classification'], name='biblio_classif_b35387_idx'),
        ),
        migrations.AddIndex(
            model_name='biblio',
            index=models.Index(fields=['opac_hide', 'promoted'], name='biblio_opac_hi_9955fa_idx'),
        ),
        migrations.AddIndex(
            model_name='biblio',
            index=models.Index(fields=['content_type_id', 'media_type_id', 'carrier_type_id'], name='biblio_content_407203_idx'),
        ),
        migrations.AddIndex(
            model_name='biblio',
            index=models.Index(fields=['uid'], name='biblio_uid_d6f88d_idx'),
        ),
    ]
