# Generated by Django 4.2.7 on 2025-12-13 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biblio',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='fines',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='loanhistory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='reserve',
            options={'managed': False},
        ),
    ]
