# Generated by Django 4.2.7 on 2025-12-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_biblio_options_alter_fines_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstauthor',
            name='authority_type',
            field=models.CharField(default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='mstpublisher',
            name='input_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
